import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Script from "next/script";


// Declare appswitcher global
declare global {
    interface Window {
        appswitcher?: {
            mount: (containerId: string, config: { configUrl: string }) => void;
        };
    }
}


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
        <head>
            <Script src="/dc_MFLoader.js" strategy="beforeInteractive"/>
            <Script id="init-minicart" strategy="afterInteractive">
                {`
              dcMicroFrontendLoader.init([
                { microapp: 'appswitcher', microappUrl: '/mfe/' }
              ]);
            `}
            </Script>
            <Script id="init-minicart" strategy="afterInteractive">
                {`
              dcMicroFrontendLoader.init([
                { microapp: 'appswitcher', microappUrl: 'https://accounts.stage.az.digicert.net' }
              ]);
            `}
            </Script>
        </head>
        <body className={"bg-white"}>
        {children}
        </body>
        </html>
    );
}
